# <center> get evolving temperature for academic paper

In [1]:
import networkx as nx
import pandas as pd
from scipy import sparse
import numpy as np
from time import perf_counter
from sklearn.preprocessing import MinMaxScaler
from itertools import product, combinations, chain
from copy import deepcopy

## domain

In [2]:
class Domain:
    '''
    Domain with one pionneering paper
    '''
    def __init__(self):
        self.G = nx.DiGraph()  # citation graph
        self.pioneer_node = 0  # pionneering node id in G, not the original one
        self.num_of_nodes = 0 
        self.num_of_edges = 0
        
        self.skeleton_tree = nx.DiGraph()
        self.node_node_reduction_index = None
        self.node_network_reduction_index = None
        self.node_node_average_step = 0
        
        self.average_temperature = 0
        self.average_growth_temperature = 0
        self.average_struct_temperature = 0
        self.volume = 0  # int
        self.mass = 0  # float
        self.node_tree_entropy = None # structure entropy based on skeleton tree
        self.node_temperature = None
        self.evolving_until_yr = 0
        self.birth_yr = 0
        
        self.von_neumann_entropy = 0 # G's von-Neumann entropy
        
    def setBirthYear(self, yr):
        self.birth_yr = yr
        
    def evolve(self, df, lead_paper_id, start_yr, step=1):
        '''
        Evolve ahead and reinitialize parameters
        Input: 
            df: pd.DataFrame, reference information
            lead_paper_id: int, ID of the pioneering work
            start_yr: int, current timestamp
            step: int, evolution window (in year)
        '''
        # extract reference for a year
        df_t = df[(df['year']>= start_yr) & (df['year']< start_yr+step)][['paper_id','reference_id']]
        G_t = nx.from_pandas_edgelist(df_t, source = 'reference_id', target = 'paper_id', create_using = nx.DiGraph)
        self.G.add_nodes_from(G_t.nodes)
        self.G.add_edges_from(G_t.edges)
        
        # add self-loop for pioneer paper (if no self-loop yet in G)
        self.G.add_edge(lead_paper_id, lead_paper_id)

        # initialize class attributes
        self.pioneer_node = np.argwhere(np.array(self.G.nodes)==lead_paper_id).flatten()[0]
        self.num_of_nodes = self.G.number_of_nodes()
        self.num_of_edges = self.G.number_of_edges()
        self.node_node_reduction_index = np.zeros((self.num_of_nodes, self.num_of_nodes))
        self.node_network_reduction_index = np.empty(self.num_of_nodes)
        self.node_tree_entropy = np.empty(self.num_of_nodes)
        self.node_temperature = np.empty(self.num_of_nodes)
        self.evolving_until_yr = min(start_yr+step-1, 2020)
        
        # clear last round's weight attribute
        for (n1, n2, d) in self.G.edges(data=True):
            d.clear()
        
        self.von_neumann_entropy = 0
        self.average_temperature = 0
        self.average_growth_temperature = 0
        self.average_struct_temperature = 0
        
    def getVonNeumannEntropy(self):
        '''
        Compute G's von neumann entropy 
        '''
        for c in sorted(nx.strongly_connected_components(self.G), key=len, reverse=True):
            sc_node_num = len(c)
            if sc_node_num>1:
                sub_G = self.G.subgraph(c).copy()
                # add weight attr 
                nx.set_edge_attributes(sub_G, 1,'weight')
                # get res
                res = sum([wgt**2 * sub_G.in_degree(u)/sub_G.in_degree(v)/sub_G.out_degree(u)**2 \
                           for (u,v,wgt) in sub_G.edges.data('weight')])  #combinations(c, 2):   
                self.von_neumann_entropy += 1-1/sc_node_num - res/2/sc_node_num**2
            else:
                # strongly connected component containing 1 node
                # von neumann entropy = 0
                break   
    
    def setNodeReductionIdx(self):
        '''
        Compute node-node and node-network reduction index
        Output:
            Reduction_idx: a 2-D array of size (# node number * # node number)
        '''
        node_embeddings = self.getNodeEmbedding()
        # node distance in embedding space
        sparse_distance_mtrx = sparse.csr_matrix(self.getNodeDistance(node_embeddings.A))  # matrix.A  convert from matrix to ndarray
        # weighted sparse adj matrix 
        sparse_adjacency_mtrx  = nx.to_scipy_sparse_matrix(self.G)
        sparse_weighted_adj_mtrx = sparse_adjacency_mtrx.multiply(sparse_distance_mtrx) # element wise multiplication
        # maximal node-pair distance in embedding space
        max_distance = sparse_weighted_adj_mtrx.max()
        # build weighted graph from sparse adj matrix
        weighted_G = nx.from_scipy_sparse_matrix(sparse_weighted_adj_mtrx, create_using = nx.DiGraph, edge_attribute='weight')
        # average node pair shortest distance 
        shortest_paths = dict(nx.all_pairs_dijkstra_path(weighted_G, weight='weight'))
        self.node_node_average_step = self.getAvgStep(shortest_paths)
        
        # node-node reduction index
        wgts = nx.get_edge_attributes(weighted_G, 'weight')
        for i,j in product(range(self.num_of_nodes),range(self.num_of_nodes)):  # i --> j, find j's predecessors
            if i==j:
                continue 
            # get all shortest paths from i to j's references     
            paths = list([shortest_paths[i].get(pre_j, []) for pre_j in weighted_G.predecessors(j)])
            for p in paths:
                if not p:  # if p is an empty list
                    self.node_node_reduction_index[i,j] += max_distance * self.node_node_average_step
                if len(p)>1:  # len(p)==1, path to itself, self-loop, no reduction     
                    self.node_node_reduction_index[i,j] += np.sum([wgts[(p[i],p[i+1])] for i in range(len(p)-1)]) 
        
        # add edge weight
        mapping = {i:u for i,u in enumerate(self.G.nodes)}
        nx.relabel_nodes(weighted_G, mapping, copy = False)
        self.G = weighted_G
        
        # node-network reduction index
        self.node_network_reduction_index = self.node_node_reduction_index.T @ np.ones((self.num_of_nodes,1))
    
    def buildSkeletonTree(self):
        '''
        Build skeleton tree by trimming citation graph
       
        '''
        # skeleton tree
        T = deepcopy(self.G)
        
        ### Step 1
        # detect loops in T
        # cut an edge whose extremities have the biggest difference in reduction index 
        # keep graph connectivity 
        for i, src in enumerate(list(T.nodes)):
            for target in list(T.nodes)[i+1:]: # src != target
                if nx.has_path(T, src, target) and nx.has_path(T, target, src):
                    has_loop = True
                    while has_loop:
                        try:
                            loop = nx.shortest_path(T, source=src, target=target)[:-1] + \
                                   nx.shortest_path(T, source=target, target=src)
                            self.cutEdgeInLoop(T, loop)
                        except:
                            has_loop = False

        ### Step 2
        # leave only one predecessor/reference for each paper
        # remove directed edges
        domain_nodes = T.nodes
        for i,n in enumerate(domain_nodes):
            pre_n = list(T.predecessors(n))
            pre_n_idx = [np.argwhere(np.array(domain_nodes)==j).flatten()[0] for j in pre_n]
            self_network_reduction_idx = self.node_network_reduction_index[i]
            if len(pre_n)>1:
                delta_reduction_idx = np.array([abs(self.node_network_reduction_index[j] -
                                                    self_network_reduction_idx) for j in pre_n_idx])
                reference_to_keep = pre_n.pop(np.argmin(delta_reduction_idx))      
                for src in pre_n:
                    T.remove_edge(src, n)          
                    
        self.skeleton_tree = T   
        
    def setNodeTreeEntropy(self):
        '''
        Compute tree entropy based on skeleton tree
        Output:
            T: nx.graph.DiGraph, same skeleton tree with tree entropy added as a node attribute
        '''
        T = self.skeleton_tree
        m = T.number_of_edges()
        node_set = set(T.nodes)
    
        for i,n in enumerate(T.nodes):
            if i==self.pioneer_node:
                self.node_tree_entropy[i] = 0
            else:    
                A_set = self.getSubTreeNodes([n])
                n_parents = list(T.predecessors(n))
                sub_parent_T_nodes  = self.getSubTreeNodes(n_parents)
                sub_T_volume = max(nx.volume(T, list(A_set), weight = None),1)  # sub_T_nodes
                if sub_parent_T_nodes:
                    self.node_tree_entropy[i] = -sub_T_volume/(2*m)*np.log(len(A_set)/len(sub_parent_T_nodes))
                else:
                    self.node_tree_entropy[i] = 0  # isolated node
                
    def setStructTemperature(self, T):
        self.average_struct_temperature = T
    
    def getAvgTemperature(self, is_initial = True, is_big_graph = True, old_avg_temperature = 0, old_V = 0, old_N = 0):
        '''
        Compute volume, mass and average temperature based on skeleton tree
        Input: 
            is_initial: boolean, whether time stamp = 0
            old_avg_temperature: float, average growth temperature for the last time stamp
            old_V: int, volume of the last time stamp
            old_N: float, mass of the last time stamp       
        '''
        ###### get average growth temperature 
        Tree = self.skeleton_tree
        # volume
        self.volume = self.num_of_nodes
        # rescale node-node reduction index
        scaler = MinMaxScaler()
        scaled_node_reduction_index = scaler.fit_transform(self.node_node_reduction_index)
        # mass
        tree_adj = nx.to_scipy_sparse_matrix(Tree).todense()
        tree_adj = np.where(tree_adj == 0,tree_adj, 1)
        self.mass = self.num_of_nodes - np.sum(np.multiply(scaled_node_reduction_index, tree_adj))
        # scaling coef
        coef = 10 if is_big_graph else 100
        if is_initial:
            # entropy 
            S = np.sum(self.node_tree_entropy)
            # set default constant
            R = 8
            c = 1 
            self.average_growth_temperature =  coef * np.exp(S/(c*self.mass)) * np.float_power(self.mass/self.volume,R/c)
        else:
            self.average_growth_temperature = old_avg_temperature * (self.volume/old_V) * (old_N/self.mass)
        print("volume:{}, mass:{}, T_growth:{}".format(self.volume, self.mass, self.average_growth_temperature))  
        
        ###### get average temperature
        self.average_temperature = self.average_growth_temperature + abs(self.average_struct_temperature)
            
    
    def spreadTemperature(self, former_population = 0):
        '''
        Compute node knowledge temperature
        Input: 
            former_population: int, node number by the end of last timestamp
        '''
        # get inactive nodes 
        coldest_nodes = self.getInactiveNodes(former_population)
            
        # add distance attribute to domain reference graph
        scaler = MinMaxScaler(feature_range = (0.5,1.5))
        scaled_node_node_reduction_idx = scaler.fit_transform(self.node_node_reduction_index)
        node_list = list(self.G.nodes)
        for u,v in self.G.edges:
            self.G.edges[u,v]['distance'] = scaled_node_node_reduction_idx[node_list.index(u)][node_list.index(v)] 

        # get node temperature     
        self.node_temperature = self.diffuseHeat(self.pioneer_node, coldest_nodes, int(self.node_node_average_step))   
        
                        
    ########## auxiliary functions ##########
    def getNodeEmbedding(self):
        '''
        Get spectral embedding
        '''
        sparse_adjacency_mtrx  = nx.to_scipy_sparse_matrix(self.G)
        sparse_degree_mtrx = np.diagflat(sparse_adjacency_mtrx.T @ np.ones((sparse_adjacency_mtrx.shape[0],1), dtype=int))
        # Laplacian matrix 
        L = sparse_degree_mtrx - sparse_adjacency_mtrx.T
        # regular Laplacian matrix
        L_regular = np.sqrt(sparse_degree_mtrx) @ L @ np.sqrt(sparse_degree_mtrx)       
        # node embedding (projected dimension = # node number)
        _, eigvecs = np.linalg.eig(L_regular)
        return eigvecs
    
    def getNodeDistance(self, M):
        '''
        Create distance matrix in embedding space 
        Extract node-pair distance for the graph
        Input: 
            M: 2-D ndarray, eigenvectors of the regular Laplacian matrix, each row is a vector
        Output:
            D: 2-D ndarray, distance matrix of the graph
        '''
        N = M.shape[0]
        D = np.empty(M.shape)
        for i in range(N):
            for j in range(i, N):
                d = np.linalg.norm(M[i] - M[j]) # 2-norm
                D[i,j], D[j,i] = d, d
        return D 
                        
    def getAvgStep(self, paths):
        '''
        Get the average shortest path in citation graph
        Input: 
            paths: dict of lists, shortest paths dictionary
        Output: 
            float, average shortest path length
        '''
        total_step = 0
        path_counter = 0                        
        for path_dict in paths.values():
            steps = [len(p)-1 for p in path_dict.values()]
            total_step += np.sum(steps)
            path_counter += len(path_dict)-1
        return total_step/path_counter               
    
    def cutEdgeInLoop(self, T, loop):
        '''
        Cut an edge in a loop in skeleton tree
        Input:
            T: networkx.graph.DiGraph, skeleton tree
            loop: list of int, represents a loop
        Output:
            None. T is already modified (dict object is changeable) 
        '''
        nodes = np.array(T.nodes)
        is_cut = False
        edges_to_cut = dict([((loop[i], loop[i+1]), 
                              abs(self.node_network_reduction_index[i+1] - self.node_network_reduction_index[i])) 
                             for i in range(len(loop)-1)])
        edges_to_cut = sorted(edges_to_cut.items(), key = lambda x: x[1], reverse=True) # sort by network reduction index 
        for edge,val in edges_to_cut:
            if len(list(T.predecessors(edge[1]))) > 1:
                T.remove_edge(edge[0], edge[1])
                is_cut = True
        if not is_cut:
            T.remove_edge(edges_to_cut[0][0][0], edges_to_cut[0][0][1])
                    
    def getSubTreeNodes(self, parents):
        '''
        Find all the children of node n in domain skeleton tree, BFS search
        Input:
            parents: list of int, root nodes' ids
        Output:
            sub_T_nodes: set of int, all child nodes of parents and parents themselves
        '''
        sub_T_nodes = set()
        child_nodes_to_parse = parents
        while child_nodes_to_parse:
            p = child_nodes_to_parse.pop(0)
            sub_T_nodes.add(p)
            child_nodes_to_parse.extend(list(self.skeleton_tree.successors(p))) # p has direct children
        return sub_T_nodes
    
    def getInactiveNodes(self, former_population = 0):
        '''
        Input:
            former_population: int, node number by the end of last time stamp
        Output:
            inactive_leaves: list of int, inactive node ids
        '''
        inactive_leaves = list()
        for i,n in enumerate(self.G.nodes):
            children = list(self.G.successors(n))
            if not children:
                inactive_leaves.append(i) 
            elif i < former_population and max(children)<former_population:
                inactive_leaves.append(i)
        return inactive_leaves
    
    def diffuseHeat(self, hottest_nodes, coldest_nodes, num_of_round):
        '''
        Compute heat diffusion over a skeleton tree
        Input:
            G: nx.graph.DiGraph,  loopless graph with node attribute 'tree_entropy'
            hottest_nodes: list of int, nodes at temperature 1
            coldest_nodes: list of int, nodes at temperature 0
            num_of_round: int, number of steps    
        Output: 
            Temperatures: ndarray, node temperature list after num_of_round steps 
        '''    
       
        adjacency = nx.to_scipy_sparse_matrix(self.G, weight = 'distance').T   
        n = adjacency.shape[0]
        Temperatures = 0.5 * np.ones(n, float)
        sources = np.array(hottest_nodes)  
        targets = np.array(coldest_nodes)

        # fix source and target temperature
        Temperatures[sources] = 1 # red
        Temperatures[targets] = 0  # blue

        # compute transition matrix
        wgts = adjacency.dot(np.ones(n))
        inverse_weight_matrix = sparse.diags(1 / wgts, format='csr')
        P = inverse_weight_matrix.dot(adjacency)

        
        # heat diffusion 
        Temperatures = P.T.dot(Temperatures)
        Temperatures = (Temperatures - min(Temperatures))/(max(Temperatures) - min(Temperatures))
        Temperatures[sources] = 1   
        Temperatures[targets] = 0
        for i in range(num_of_round):
            Temperatures = P.dot(Temperatures)   
            # fix source and target temperature
            Temperatures[sources] = 1   
            Temperatures[targets] = 0    

        # rescale temperature    
        mean_T = np.mean(Temperatures)    
        Temperatures *= self.average_temperature/mean_T    
        return Temperatures
    
  
    

### $T_{struct}^t$ ---- shrink $G^{t+1}$

In [3]:
def get_von_neumann_E_shrinked(prev_G, G, node_df):
    '''
    Shrink current citation graph to a graph induced by nodes in prev_G
    Get von neumann entropy on the shrinked graph
    Input:
        prev_G: nx.DiGraph, citation graph by the end of last timestamp
        G: nx.DiGraph, current citation graph
        node_df: pd.DataFrame, columns = ['paper_id','year']
    Output:
        E: float, von neumann entropy of the graph shrinked from G
    '''
    
    if not prev_G.number_of_nodes():
        return 0,0
    
    node_df = node_df.set_index('paper_id')
    new_edge_wgt_sum = 0
    # shrink network
    nx.set_edge_attributes(G, 1,'weight')
    nodes_to_rm = set(G.nodes).difference(set(prev_G.nodes))
    for n in nodes_to_rm:
        parents_n = set(G.predecessors(n))
        if len(parents_n) == 1:
            for c in G.successors(n):
                G.add_edge(next(iter(parents_n)), c, weight = G[n][c]['weight']/2) 
            G.remove_node(n)
        else:
            # more than 1 parent
            # find all youngest ancestor nodes in prev_G
            # add virtual edges between them, weight = 1/# youngest ancestor nodes
            ancestors_n = parents_n
            wgt_shared = sum([G[p][n]['weight'] for p in ancestors_n])
            tmp = ancestors_n.intersection(nodes_to_rm)
            while tmp:
                tmp_ancestors = []
                tmp_ancestors.extend([list(G.predecessors(k)) for k in tmp])
                tmp_ancestors = list(chain.from_iterable(tmp_ancestors))  # unlist nested list
                ancestors_n.union(set(tuple(tmp_ancestors)))
                ancestors_n -= tmp # set difference
                tmp = ancestors_n.intersection(nodes_to_rm)
            num_of_ancestors = len(ancestors_n)
            if num_of_ancestors > 1:
                # add edge
                ancestors_dict = dict([(i, node_df.at[i, 'year']) for i in ancestors_n])
                for u_dict,v_dict in combinations(ancestors_dict.items(),2):
                    if not prev_G.has_edge(u_dict[0], v_dict[0]) and not prev_G.has_edge(u_dict[0], v_dict[0]):
                        if not G.has_edge(u_dict[0], v_dict[0]) and not G.has_edge(v_dict[0], u_dict[0]): # 取第一条边
                            if u_dict[1] < v_dict[1]: 
                                G.add_edge(u_dict[0], v_dict[0], weight = 2*wgt_shared/num_of_ancestors/(num_of_ancestors-1))
                            elif u_dict[1] > v_dict[1]:
                                G.add_edge(v_dict[0], u_dict[0], weight = 2*wgt_shared/num_of_ancestors/(num_of_ancestors-1))   
                            else: # paper on same year, bidirectional edges
                                G.add_edge(u_dict[0], v_dict[0], weight = wgt_shared/num_of_ancestors/(num_of_ancestors-1))
                                G.add_edge(v_dict[0], u_dict[0], weight = wgt_shared/num_of_ancestors/(num_of_ancestors-1))
                            new_edge_wgt_sum += 2*wgt_shared/num_of_ancestors/(num_of_ancestors-1)    
                G.remove_node(n)
            
     # get entropy
    E = 0
    for c in sorted(nx.strongly_connected_components(G), key=len, reverse=True):
        sc_node_num = len(c)
        if sc_node_num>1:
            sub_G = G.subgraph(c).copy()
            # get res
            res = sum([wgt**2 * sub_G.in_degree(u)/sub_G.in_degree(v)/sub_G.out_degree(u)**2 \
                       for (u,v,wgt) in sub_G.edges.data('weight')])  #combinations(c, 2):   
            E += 1-1/sc_node_num - res/2/sc_node_num**2
            for u,v in combinations(sub_G.nodes,2):
                if sub_G.has_edge(u,v) and sub_G.has_edge(v,u):
                    E -= sub_G[u][v]['weight']*sub_G[v][u]['weight']/sub_G.in_degree(v)/sub_G.out_degree(u)
        else:
            # strongly connected component containing 1 node
            # von neumann entropy = 0
            break
    return E, new_edge_wgt_sum

## read input

In [4]:
ref_df = pd.read_csv(r'99188113domain_reference.csv')
ref_df.head()

paper_id  reference_id  year
0    8777697      99188113  1995
1  498094871      99188113  1995
2  352699142      99188113  1995
3   39453343      99188113  1995
4  470391866      99188113  1995

In [5]:
paper_df = pd.read_csv(r'99188113domain_paper.csv')
paper_df.head()

paper_id  year
0  352699142  1993
1   47465484  1993
2   34702267  1993
3   39453343  1994
4  498094871  1994

## run single-domain T evolution

In [6]:
def getEvolvingTemperature(ref_df, paper_df, lead_paper_id, evolve_step=1):
    '''
    Compute evolving node temperature based on mainly domain skeleton tree and node tree entropy
    Visualise every evolve_step-year
    Input: 
        ref_df: pandas Dataframe, columns = ['paper_id','reference_id','year']
        paper_df:  pandas Dataframe, columns = ['paper_id','year']
        lead_paper_id: int, original id of the pionneering work
        evolve_step: interval between 2 visualization, unit: year 
    Output:
        None
    '''
    domain = Domain()
    start_year = ref_df['year'].min()
    end_year = ref_df['year'].max()
    T = int((end_year - start_year)/evolve_step)
    delta = (end_year - start_year)%evolve_step 
    domain.setBirthYear(start_year)
    
    # record network size and average temperature for visualization
    yr_stamps = list()
    yr_node_number = list()
    yr_edge_number = list()
    yr_mass = list()
    yr_volume = list()
    yr_avg_growth_temperatures = list()
    
    von_neumann_entropies = list()
    von_neumann_entropies_shrink = list()
    yr_avg_struct_temperatures = list()
    
    is_big_graph = True if paper_df.shape[0]>5000 else False
    
    for t in range(T+1):
        
        print('round',t)
        t3 = perf_counter()
        
        prev_G = deepcopy(domain.G)
        
        t1 = perf_counter()
        domain.evolve(ref_df, lead_paper_id, start_year+delta+t*evolve_step, evolve_step)
        print('Evolve domain elapsed time: {}s'.format(perf_counter() - t1))
        
        if t>=1:
            # get equivalent shrinked network, remove all new nodes, add edges between old nodes
            curr_G = deepcopy(domain.G)
            H, delta_edge_sum = get_von_neumann_E_shrinked(prev_G, curr_G, paper_df)
            H_prev = von_neumann_entropies[-1]
            try:
                struct_Temperature = delta_edge_sum/(H - H_prev) if delta_edge_sum else 0
            except: # float division by 0 error
                struct_Temperature = 10*delta_edge_sum
            avg_struct_T = struct_Temperature/domain.num_of_nodes 
            domain.setStructTemperature(avg_struct_T)
            print('old E: {o}, new_E: {n}, struct_T: {T}'.format(o=H_prev,n=H,T= avg_struct_T))
    
            von_neumann_entropies_shrink.append(H)
            yr_avg_struct_temperatures.append(avg_struct_T)
        else:
            # first round, no struct change
            yr_avg_struct_temperatures.append(0)
            domain.setStructTemperature(0)
            
        domain.getVonNeumannEntropy()
        von_neumann_entropies.append(domain.von_neumann_entropy)
        
        
        t1 = perf_counter()
        domain.setNodeReductionIdx()
        print('Get node reduction index elapsed time: {}s'.format(perf_counter() - t1))
        
       
        t1 = perf_counter()
        domain.buildSkeletonTree()
        print("Build skeleton tree elapsed time: {}s".format(perf_counter() - t1))
        
        
        # compute tree entropy
        t1 = perf_counter()    
        domain.setNodeTreeEntropy()
        print("Compute tree entropy elapsed time: {}s".format(perf_counter() - t1))
 
  
        # compute domain average temperature and node temperature
        t1 = perf_counter()
        if t == 0:    
            domain.getAvgTemperature(is_initial = True, is_big_graph = is_big_graph)
            domain.spreadTemperature(former_population = 0)
        else:    
            domain.getAvgTemperature(is_initial = False, is_big_graph = is_big_graph,
                                                         old_avg_temperature = yr_avg_growth_temperatures[-1],
                                                         old_V = yr_volume[-1],
                                                         old_N = yr_mass[-1])
            domain.spreadTemperature(former_population = yr_node_number[-1])
        print("Compute average and node temperature elapsed time: {}s".format(perf_counter() - t1))
          
        
        # export node info
        df_node_export = pd.DataFrame({'id':list(domain.G.nodes),'T': domain.node_temperature})       
        df_node_export['tree_entropy'] = domain.node_tree_entropy
        df_node_export.to_csv(str(lead_paper_id)+'node_'+ str(domain.evolving_until_yr)+'.csv', index = False)
        # export edge info
        df_edge_export = pd.DataFrame(list(domain.skeleton_tree.edges))
        df_edge_export.columns = ['reference_id','paper_id']
        df_edge_export.to_csv(str(lead_paper_id)+'edge_'+ str(domain.evolving_until_yr)+'.csv', index = False)
        
        
        t4 = perf_counter()
        print('total running time: {}s'.format(t4-t3))
        print()
        
        yr_stamps.append(domain.evolving_until_yr)
        yr_node_number.append(domain.num_of_nodes)
        yr_edge_number.append(domain.num_of_edges)  
        yr_mass.append(domain.mass)
        yr_volume.append(domain.volume)
        yr_avg_growth_temperatures.append(domain.average_growth_temperature)

        
    d = {'year':yr_stamps, 'node number':yr_node_number,
         'edge number':yr_edge_number, 'mass':yr_mass, 'volume': yr_volume,
         'T_growth_t': yr_avg_growth_temperatures,'T_struct_t': abs(np.array(yr_avg_struct_temperatures)),
         'T_t':np.array(yr_avg_growth_temperatures)+abs(np.array(yr_avg_struct_temperatures))}    
    df_network_evolve_info = pd.DataFrame(data=d)
    with pd.ExcelWriter(str(lead_paper_id)+' domain stats.xlsx') as writer:
        df_network_evolve_info.to_excel(writer)

In [7]:
# call function
pioneer_id = 99188113
getEvolvingTemperature(ref_df, paper_df, pioneer_id, evolve_step = 3)

round 0
Evolve domain elapsed time: 0.00860419267947205s
von neumann entropy
2.291361239711934
Get node reduction index elapsed time: 2.2236642273839777s
Build skeleton tree elapsed time: 0.8759111166902862s
Compute tree entropy elapsed time: 0.20541950243710794s
volume:586, mass:494.41769774908636, T_growth:2.5829223433433177
Compute average and node temperature elapsed time: 0.035238014304236565s
total running time: 3.3738805751737604s

round 1
Evolve domain elapsed time: 0.0159661177957382s
old E: 2.291361239711934, new_E: -4.415954206355881, struct_T: -0.008222634842834385


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


von neumann entropy
8.763838737119505
Get node reduction index elapsed time: 51.708900355190494s
Build skeleton tree elapsed time: 12.499493819163497s
Compute tree entropy elapsed time: 2.77261355393955s
volume:2235, mass:1779.6617842431435, T_growth:2.7368298243623146


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


Compute average and node temperature elapsed time: 0.3258859575104225s
total running time: 67.48784972053387s

round 2
Evolve domain elapsed time: 0.03377007224756312s
old E: 8.763838737119505, new_E: 7.2155948014382965, struct_T: -0.08949668063093381
von neumann entropy
16.418897134560595
Get node reduction index elapsed time: 346.6668504973478s
Build skeleton tree elapsed time: 64.14653538523163s
Compute tree entropy elapsed time: 12.390054031410386s
volume:4761, mass:3564.2200526686192, T_growth:2.910994690510742


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


Compute average and node temperature elapsed time: 1.5037929182639118s
total running time: 425.29426649266225s

round 3
Evolve domain elapsed time: 0.06945449890918098s
old E: 16.418897134560595, new_E: 15.182690365136965, struct_T: -0.13653136725976528
von neumann entropy
20.386706741042076
Get node reduction index elapsed time: 1337.4071647420278s
Build skeleton tree elapsed time: 194.6638366850109s
Compute tree entropy elapsed time: 38.15902012134916s
volume:8058, mass:5785.872129731568, T_growth:3.035052255184996


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


Compute average and node temperature elapsed time: 4.3217416570082605s
total running time: 1576.0383600798748s

round 4
Evolve domain elapsed time: 0.1346931161874636s
old E: 20.386706741042076, new_E: 33.96737163060811, struct_T: 0.011684745727391982
von neumann entropy
24.014021555856893
Get node reduction index elapsed time: 4951.16711548857s
Build skeleton tree elapsed time: 400.4496229296574s
Compute tree entropy elapsed time: 76.38764954020553s
volume:11202, mass:7789.448917998839, T_growth:3.1339825630751776


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


Compute average and node temperature elapsed time: 8.892258060193853s
total running time: 5439.659167691311s

round 5
Evolve domain elapsed time: 0.22855924819305073s
old E: 24.014021555856893, new_E: 49.578858756780186, struct_T: 0.005061165978015126
von neumann entropy
27.253604889190225
Get node reduction index elapsed time: 8037.761105917854s
Build skeleton tree elapsed time: 659.6993603185947s
Compute tree entropy elapsed time: 119.81500333398799s
volume:13788, mass:9374.213160838674, T_growth:3.2053406485253233


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


Compute average and node temperature elapsed time: 16.069393848887557s
total running time: 8837.240443125971s

round 6
Evolve domain elapsed time: 0.29649467566923704s
old E: 27.253604889190225, new_E: 6.7774620693316905, struct_T: -0.00427444415316323
von neumann entropy
28.26054933363467
Get node reduction index elapsed time: 11438.462741670057s
Build skeleton tree elapsed time: 924.6808624150763s
Compute tree entropy elapsed time: 161.51702837468838s
volume:15763, mass:10605.174812853717, T_growth:3.2391330318830933


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


Compute average and node temperature elapsed time: 30.13359295303235s
total running time: 12559.760697588068s

round 7
Evolve domain elapsed time: 0.2671897848449589s
old E: 28.26054933363467, new_E: -16.48999816017973, struct_T: -0.0010508305097180152
von neumann entropy
28.76054933363467
Get node reduction index elapsed time: 14237.12583327662s
Build skeleton tree elapsed time: 1116.6680800707181s
Compute tree entropy elapsed time: 200.4992268885544s
volume:16927, mass:11352.527141339822, T_growth:3.2493402213721305


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


Compute average and node temperature elapsed time: 42.23266546613013s
total running time: 15602.421632592755s

round 8
Evolve domain elapsed time: 0.34853345077863196s
old E: 28.76054933363467, new_E: -56.13302849005679, struct_T: -5.531978134770794e-05
von neumann entropy
28.76054933363467
Get node reduction index elapsed time: 14346.428840071887s
Build skeleton tree elapsed time: 1117.3819939258246s
Compute tree entropy elapsed time: 219.89368509875203s
volume:17046, mass:11431.177148790819, T_growth:3.2496700673032475


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


Compute average and node temperature elapsed time: 41.69318706335616s
total running time: 15733.072351947834s



## domain group

In [4]:
class DomainGroup(Domain):
    '''
    A group of domains with similar research interests. Each domain is an object of Class Domain.
    '''
    def __init__(self, num, T):
        self.domain_number = 0
        self.domains = list()
        self.domain_ages = np.zeros(num, dtype = int)

        self.domain_avg_temperatures = np.zeros([T, num])
        self.domains_helped = list() 
        self.total_rounds = T
        self.current_round = 0
    
    def initializeDomains(self, start_yrs):
        # create domains
        for yr in start_yrs:
            d = Domain()
            d.setBirthYear(yr)
            self.domains.append(d)
        
    def setDomainAvgTemperatures(self, t, domain_idx, is_born = True):
        if not is_born or self.domains[domain_idx].evolving_until_yr == self.domains[domain_idx].birth_yr:
            self.domain_avg_temperatures[t, domain_idx] = -1
        else:
            self.domain_avg_temperatures[t, domain_idx] = self.domains[domain_idx].average_temperature
        
    def updateDomainAges(self):
        self.domain_ages = np.array([d.evolving_until_yr - d.birth_yr for d in self.domains])
        self.domain_ages = np.where(self.domain_ages < 0, 0, self.domain_ages)
    
    def decideHelpWho(self):
        '''
        Identify domain(s) with a declining knowledge temperature during the last evolution period
        Output:
            int, index of the stagnating domain(s) in self.domains
        '''
        recent_avg_temperature_growth = np.true_divide(self.domain_avg_temperatures[self.current_round,:],\
                                                       self.domain_avg_temperatures[self.current_round-1,:]) 
        
        if min(recent_avg_temperature_growth)>1:
             # both/all grow, no need to help
            return np.array([])
        else:
            return np.argwhere(abs(recent_avg_temperature_growth)<1).flatten()
        
   
    def adjustAvgTemp(self, target_domain_idx, t):
        '''
        Adjust the knowledge temperature of the stagnating domain(s)
        Input: 
            target_domain_idx: int, index of the stagnating domain(s) in self.domains
        Output:
            energy_to_spare: float, the amount of energy to be exchanged during forest helping 
        '''
        # get domain average temperatures before average temperature rescaling        
        age_sum = np.sum(self.domain_ages)
        
        print("domain_to_help", target_domain_idx)
        print("current avg_T")
        print(self.domain_avg_temperatures[t])
        
        # all those with a rising knowledge temperature help the rest
        energy_to_spare = 0
        for idx, d in enumerate(self.domains):
            if idx not in target_domain_idx:
                energy_to_spare += d.num_of_nodes/(1+age_sum)*self.domain_avg_temperatures[t][idx]
        return energy_to_spare        
   
    def updateDomainInHelp(self, target_domain_idx, t, delta_U):
        '''
        Perform forest helping
        Update knowledge temperature of every domain after energy transfer
        Input:
            target_domain_idx: list of int, index of domain(s) receiving energy
            t: int, current timestamp
            delta_U: float, the total amount of energy given to domain(s) in need of help
        '''
        # get knowledge temperature increment for domain(s) in need of help
        delta_T = delta_U/sum([self.domains[d].num_of_nodes for d in target_domain_idx])
        
        # update domain knowledge temperature
        for i, domain in enumerate(self.domains):
            if i in target_domain_idx:
                new_avg_T = domain.average_temperature + delta_T
            else:
                new_avg_T = domain.average_temperature * sum(self.domain_ages)/(1+sum(self.domain_ages))
            domain.node_temperature *= (new_avg_T/domain.average_temperature) 
            domain.average_struct_temperature *= (new_avg_T/domain.average_temperature)
            domain.average_growth_temperature *= (new_avg_T/domain.average_temperature)
            domain.average_temperature = new_avg_T
       
        
    
    def updateDomainGroupRecord(self, target_domain_idx = None, t = None):
        '''
        Update parameters after forest helping
        Input:
            target_domain_idx: list of int, domain(s) receiving help in this round. [] means no helping 
            t: int, current timestamp
        '''
        self.current_round += 1
        self.domain_number = len(np.nonzero(self.domain_ages)[0])
        if target_domain_idx:
            for i, domain in enumerate(self.domains):
                self.domain_avg_temperatures[t, i] = domain.average_temperature if domain.average_temperature>0 else -1
            self.domains_helped.append(target_domain_idx)
            print("updateDomainGroupRecord")
            print(self.domain_avg_temperatures)
        

## run multiple domains T evolution

In [5]:
def getEvolvingTemperatureForest(df_ref_list, df_paper_list, lead_paper_ids, evolve_step=1):
    '''
    Compute knowledge temperatures for domain groups after forest helping mechanism
    Input: 
        df_ref_list: pd.Dataframe, columns = ['paper_id','reference_id','year'], each df is a domain
        df_paper_list: pd.Dataframe, columns = ['paper_id','year'], each df is a domain
        lead_paper_ids: list of int, original ids of the pionneering work
        evolve_step: int, evolving window (in year)
    Output:
        None
    '''
    # initialize domain group
    N = len(df_ref_list)
    start_years = [df['year'].min() for df in df_ref_list]
    end_years = [df['year'].max() for df in df_ref_list]
    domain_rank = np.argsort(start_years)
    ordered_df_ref_list = list()
    ordered_df_paper_list = list()
    ordered_lead_paper_ids = list()
    for i in range(N):
        old_idx = np.argwhere(domain_rank == i).flatten()[0]
        ordered_df_ref_list.append(df_ref_list[old_idx])
        ordered_df_paper_list.append(df_paper_list[old_idx])
        ordered_lead_paper_ids.append(lead_paper_ids[old_idx])
    T = int((max(end_years) - min(start_years))/evolve_step)
    delta = (max(end_years) - min(start_years))%evolve_step  # the beginning period where there's only one domain 
    
    # initialize domains
    domain_group = DomainGroup(N, T+1)
    domain_group.initializeDomains(sorted(start_years))
    
    # judge if big graph, for T_growth_t
    are_big_graphs = list([True if df.shape[0]>5000 else False for df in ordered_df_paper_list])
    
    # record network size and average temperature for visualization
    yr_stamps = list()
    yr_node_number = np.zeros([T+1,N], dtype = int)
    yr_edge_number = np.zeros([T+1,N], dtype = int)
    yr_mass =  np.zeros([T+1,N])
    yr_volume = np.zeros([T+1,N])
    von_neumann_entropies = np.zeros([T+1,N])
    von_neumann_entropies_shrink = np.zeros([T,N])
    yr_avg_temperature = np.zeros([T+1,N])
    
    current_yr = min(start_years)+delta
    
    prev_avg_growth_temperature = np.zeros(N)
    
    for t in range(T+1):
        
        print('round',t)
        t3 = perf_counter()
        
        print('Current year', current_yr)
        
        t1 = perf_counter()
        for domain_idx, (domain, lead_paper_id, df, paper_df,is_big_graph) in enumerate(zip(domain_group.domains,
                                                                                   ordered_lead_paper_ids, 
                                                                                   ordered_df_ref_list,
                                                                                   ordered_df_paper_list,
                                                                                   are_big_graphs)):
            
            if domain.birth_yr >= current_yr+evolve_step:
                # not born by the end of this round
                domain_group.setDomainAvgTemperatures(t, domain_idx, is_born = False)
                continue    
            
            prev_G = deepcopy(domain.G)
                
            domain.evolve(df, lead_paper_id, current_yr, evolve_step)
            
            if prev_G.number_of_nodes():
                # get equivalent shrinked network, remove all new nodes, add edges between old nodes
                curr_G = deepcopy(domain.G)
                H, delta_edge_sum = get_von_neumann_E_shrinked(prev_G, curr_G, paper_df)
                H_prev = von_neumann_entropies[t-1, domain_idx]
                try:
                    struct_Temperature = delta_edge_sum/(H - H_prev) if delta_edge_sum else 0
                except: # float division by 0 error
                    struct_Temperature = 10*delta_edge_sum  
                avg_struct_T = struct_Temperature/domain.num_of_nodes 
                domain.setStructTemperature(avg_struct_T)
                von_neumann_entropies_shrink[t-1, domain_idx] = H
            else:
                # first round, no struct change
                domain.setStructTemperature(0)
            
            domain.getVonNeumannEntropy()
            von_neumann_entropies[t, domain_idx] = domain.von_neumann_entropy
       
            domain.setNodeReductionIdx()
          
            domain.buildSkeletonTree()
        
            domain.setNodeTreeEntropy()

            ## compute domain average temperature and node temperature
            if prev_G.number_of_nodes() == 0:    
                domain.getAvgTemperature(is_initial = True, is_big_graph = is_big_graph)
                domain.spreadTemperature(former_population = 0)
            else:    
                domain.getAvgTemperature(is_initial = False, is_big_graph = is_big_graph,
                                         old_avg_temperature = prev_avg_growth_temperature[domain_idx],
                                         old_V = yr_volume[t-1, domain_idx],
                                         old_N = yr_mass[t-1, domain_idx])
                domain.spreadTemperature(former_population = yr_node_number[t-1, domain_idx])
            
            # update group avg temperature
            domain_group.setDomainAvgTemperatures(t, domain_idx)
                
        print("Evolve domain group: {}s".format(perf_counter() - t1))
        
        
        print("avg_T before adjustment: ")    
        print([d.average_temperature for d in domain_group.domains])
        
        print("avg_struct_T:")
        print([d.average_struct_temperature for d in domain_group.domains])
        
        domain_group.updateDomainAges()
        print("domain ages:", domain_group.domain_ages)
        
        if domain_group.domain_number >= 2:
            # forest helping mechanism
            t1 = perf_counter()
            domain_to_help = domain_group.decideHelpWho()
            print("domain_to_help", domain_to_help)
            if len(list(domain_to_help)):
                energy_to_share = domain_group.adjustAvgTemp(domain_to_help, t) 
                domain_group.updateDomainInHelp(domain_to_help, t, energy_to_share)
            domain_group.updateDomainGroupRecord(list(domain_to_help), t)
            print("Forest helping: {}s".format(perf_counter() - t1))
        else:
            domain_group.updateDomainGroupRecord()
            
        # output domain group evolution after forest helping  
        for i, (domain, lead_paper_id) in enumerate(zip(domain_group.domains, ordered_lead_paper_ids)):
#             # export node info
#             df_node_export = pd.DataFrame({'id':list(domain.G.nodes),'T': domain.node_temperature})       
#             df_node_export['tree_entropy'] = domain.node_tree_entropy
#             df_node_export.to_csv(str(lead_paper_id)+'node_'+str(t)+'_'+ str(domain.evolving_until_yr)+'.csv', index = False)
#             # export edge info
#             df_edge_export = pd.DataFrame(list(domain.skeleton_tree.edges))
#             df_edge_export.columns = ['reference_id','paper_id']
#             df_edge_export.to_csv(str(lead_paper_id)+'edge_'+str(t)+'_'+ str(domain.evolving_until_yr)+'.csv', index = False)
            
            yr_node_number[t, i] = domain.num_of_nodes
            yr_edge_number[t, i] = domain.num_of_edges
            yr_mass[t, i] = domain.mass
            yr_volume[t, i] = domain.volume
            yr_avg_temperature[t, i] = domain.average_temperature
            prev_avg_growth_temperature[i] = domain.average_growth_temperature 
        
        yr_stamps.append(current_yr+evolve_step-1)
        current_yr += evolve_step
        
        t4 = perf_counter()
        print('total running time: {}s'.format(t4-t3))
        print()
        
    
    # output stats for each domain
    for i, (domain, pioneer_id) in enumerate(zip(domain_group.domains, ordered_lead_paper_ids)):
        d = {'year':yr_stamps, 'node number':yr_node_number[:,i],
             'edge number':yr_edge_number[:,i], 'mass':yr_mass[:,i], 'volume': yr_volume[:,i],
             'T_t forest':yr_avg_temperature[:,i]}    
        df_network_evolve_info = pd.DataFrame(data=d)
        with pd.ExcelWriter(str(pioneer_id)+' domain stats.xlsx') as writer:
            df_network_evolve_info.to_excel(writer)

In [10]:
# call function

# wireless networks
# ref_df1 = pd.read_csv(r'wireless networks forest/62270017domain_reference.csv')
# ref_df2 = pd.read_csv(r'wireless networks forest/438420345domain_reference.csv')
# paper_df1 = pd.read_csv(r'wireless networks forest/62270017domain_paper.csv')
# paper_df2 = pd.read_csv(r'wireless networks forest/438420345domain_paper.csv')

# GRU LSTM
# ref_df1 = pd.read_csv(r'RNN memory layer forest/168338164domain_reference.csv')
# ref_df2 = pd.read_csv(r'RNN memory layer forest/56158074domain_reference.csv')
# paper_df1 = pd.read_csv(r'RNN memory layer forest/168338164domain_paper.csv')
# paper_df2 = pd.read_csv(r'RNN memory layer forest/56158074domain_paper.csv')

# RNN word embeddings
ref_df1 = pd.read_csv(r'word embedding forest/223688399domain_reference.csv')
ref_df2 = pd.read_csv(r'word embedding forest/256500874domain_reference.csv')
ref_df3 = pd.read_csv(r'word embedding forest/372720438domain_reference.csv')
paper_df1 = pd.read_csv(r'word embedding forest/223688399domain_paper.csv')
paper_df2 = pd.read_csv(r'word embedding forest/256500874domain_paper.csv')
paper_df3 = pd.read_csv(r'word embedding forest/372720438domain_paper.csv')

df_ref_list = [ref_df1, ref_df2, ref_df3]
df_paper_list = [paper_df1, paper_df2, paper_df3]
lead_paper_ids = [223688399, 256500874, 372720438]
getEvolvingTemperatureForest(df_ref_list, df_paper_list, lead_paper_ids, evolve_step=2)

round 0
Current year 2004
von neumann entropy
0
volume:25, mass:16.203907793629746, T_growth:3.2970884071966475
Evolve domain group: 0.02647584947408177s
avg_T before adjustment: 
[3.2970884071966475, 0, 0]
avg_struct_T:
[0, 0, 0]
domain ages: [2 0 0]
total running time: 0.02750337366887834s

round 1
Current year 2006
von neumann entropy
0.7373611111111111
volume:61, mass:38.06798740994441, T_growth:3.424366698141683
Evolve domain group: 0.06947389281413052s
avg_T before adjustment: 
[3.5748757942930434, 0, 0]
avg_struct_T:
[0.15050909615136024, 0, 0]
domain ages: [4 0 0]
total running time: 0.06972072429198306s

round 2
Current year 2008
von neumann entropy
0.7373611111111111


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide
c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


volume:103, mass:64.2491622816236, T_growth:3.4259427565815264
von neumann entropy
0.6861979166666666
volume:24, mass:20.88296054221835, T_growth:35.06597213638032
Evolve domain group: 0.23404807501356117s
avg_T before adjustment: 
[3.576511626524099, 35.06597213638032, 0]
avg_struct_T:
[0.15056886994257238, 0, 0]
domain ages: [6 1 0]
total running time: 0.2342578817770118s

round 3
Current year 2010
von neumann entropy
0.9873611111111111


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide
c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


volume:173, mass:96.95903094402787, T_growth:3.813012102544939
von neumann entropy
0.9361979166666666
volume:113, mass:83.92659329911885, T_growth:41.081430539254875


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide
c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


Evolve domain group: 0.6888022784696659s
avg_T before adjustment: 
[3.9137335818495114, 41.19870907827267, 0]
avg_struct_T:
[0.10072147930457236, -0.1172785390177931, 0]
domain ages: [8 3 0]
Decide help who
[ 3.91373358 41.19870908 -1.        ]
[ 3.57651163 35.06597214 -1.        ]
[1.09428795 1.1748914  1.        ]
domain_to_help []
Forest helping: 0.0009654636814957485s
total running time: 0.6905748810822843s

round 4
Current year 2012
von neumann entropy
1.4943055555555556
volume:341, mass:170.71005666297856, T_growth:4.268798147096627
von neumann entropy
1.4361979166666665


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


volume:291, mass:172.36829219371072, T_growth:51.51127739936491
von neumann entropy
0
volume:29, mass:23.5, T_growth:1.977882043082873
Evolve domain group: 3.7442296971421456s
avg_T before adjustment: 
[4.3699869781853256, 52.043236201549696, 1.977882043082873]
avg_struct_T:
[0.10118883108869857, 0.5319588021847915, 0]
domain ages: [10  5  0]
Decide help who
[ 4.36998698 52.0432362  -1.        ]
[ 3.91373358 41.19870908 -1.        ]
[1.11657753 1.26322493 1.        ]
domain_to_help []
Forest helping: 0.0004442966601345688s
total running time: 3.7450251997361192s

round 5
Current year 2014


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide
c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


von neumann entropy
2.4943055555555556
volume:1050, mass:483.01618713129733, T_growth:4.645558791535432


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


von neumann entropy
1.9361979166666665
volume:889, mass:441.7800136806248, T_growth:61.399156692973726
von neumann entropy
2.0555555555555554


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


volume:1197, mass:660.2316384373203, T_growth:2.9058157299409495
Evolve domain group: 61.97128891518514s
avg_T before adjustment: 
[4.730542110901751, 61.78963036932579, 2.9671404666677326]
avg_struct_T:
[0.08498331936631819, 0.39047367635206887, 0.061324736726782916]
domain ages: [12  7  2]
Decide help who
[ 4.73054211 61.78963037  2.96714047]
[ 4.36998698 52.0432362  -1.        ]
[ 1.08250714  1.18727494 -2.96714047]
domain_to_help []
Forest helping: 0.0004460597410798073s
total running time: 61.97358762146905s

round 6
Current year 2016


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


von neumann entropy
3.8554166666666667
volume:2179, mass:1090.1620661411712, T_growth:4.27146164597828


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


von neumann entropy
2.936197916666667
volume:1766, mass:926.1557475114307, T_growth:58.179955213944396


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


von neumann entropy
7.595833333333333
volume:4136, mass:2159.2751105387424, T_growth:3.0700312999073898


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


Evolve domain group: 542.130343240322s
avg_T before adjustment: 
[4.500288680736277, 58.35840263775217, 3.3376831423735047]
avg_struct_T:
[0.2288270347579973, 0.17844742380777204, -0.26765184246611484]
domain ages: [14  9  4]
Decide help who
[ 4.50028868 58.35840264  3.33768314]
[ 4.73054211 61.78963037  2.96714047]
[0.95132621 0.9444692  1.12488208]
domain_to_help [0 1]
adjustAvgTemp
domain_to_help [0 1]
current avg_T
[ 4.50028868 58.35840264  3.33768314]
updateDomainGroupRecord
[[ 3.29708841 -1.         -1.        ]
 [ 3.57487579 -1.         -1.        ]
 [ 3.57651163 35.06597214 -1.        ]
 [ 3.91373358 41.19870908 -1.        ]
 [ 4.36998698 52.0432362  -1.        ]
 [ 4.73054211 61.78963037  2.96714047]
 [ 4.62526295 58.4833769   3.21848017]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
Forest helping: 0.002053285264992155s
total running time: 542.132827775451s

round 7
Current year 2018
von neumann entropy
4.605416666666667
volume:3157, mass:1648

c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


von neumann entropy
3.436197916666667
volume:2640, mass:1441.2875651602556, T_growth:56.007868120593486


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


von neumann entropy
11.047222222222222
volume:7736, mass:3999.5846126825813, T_growth:2.9893554429096643


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


Evolve domain group: 2150.1356970150664s
avg_T before adjustment: 
[4.258736206131108, 56.09520822816617, 3.5192992395154974]
avg_struct_T:
[0.05320026005689892, 0.08734010757268709, -0.5299437966058331]
domain ages: [16 11  6]
Decide help who
[ 4.25873621 56.09520823  3.51929924]
[ 4.62526295 58.4833769   3.21848017]
[0.92075548 0.959165   1.09346619]
domain_to_help [0 1]
adjustAvgTemp
domain_to_help [0 1]
current avg_T
[ 4.25873621 56.09520823  3.51929924]
updateDomainGroupRecord
[[ 3.29708841 -1.         -1.        ]
 [ 3.57487579 -1.         -1.        ]
 [ 3.57651163 35.06597214 -1.        ]
 [ 3.91373358 41.19870908 -1.        ]
 [ 4.36998698 52.0432362  -1.        ]
 [ 4.73054211 61.78963037  2.96714047]
 [ 4.62526295 58.4833769   3.21848017]
 [ 4.39686698 56.233339    3.41579044]
 [ 0.          0.          0.        ]]
Forest helping: 0.003033558852621354s
total running time: 2150.1403589564434s

round 8
Current year 2020
von neumann entropy
4.605416666666667
volume:3265, mass:

c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


von neumann entropy
3.436197916666667
volume:2733, mass:1503.842150949534, T_growth:55.70590578520275


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


von neumann entropy
11.047222222222222
volume:8133, mass:4199.586403644498, T_growth:2.905061018978325


c:\users\ldr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:371: RuntimeWarning: divide by zero encountered in true_divide


Evolve domain group: 2481.8792468678002s
avg_T before adjustment: 
[4.3404921576452065, 55.71546360465732, 2.92030131434172]
avg_struct_T:
[0.015426110114565277, 0.00955781945457241, 0.015240295363394874]
domain ages: [17 12  7]
Decide help who
[ 4.34049216 55.7154636   2.92030131]
[ 4.39686698 56.233339    3.41579044]
[0.98717841 0.9907906  0.85494159]
domain_to_help [0 1 2]
adjustAvgTemp
domain_to_help [0 1 2]
current avg_T
[ 4.34049216 55.7154636   2.92030131]
updateDomainGroupRecord
[[ 3.29708841 -1.         -1.        ]
 [ 3.57487579 -1.         -1.        ]
 [ 3.57651163 35.06597214 -1.        ]
 [ 3.91373358 41.19870908 -1.        ]
 [ 4.36998698 52.0432362  -1.        ]
 [ 4.73054211 61.78963037  2.96714047]
 [ 4.62526295 58.4833769   3.21848017]
 [ 4.39686698 56.233339    3.41579044]
 [ 4.34049216 55.7154636   2.92030131]]
Forest helping: 0.002019786712480709s
total running time: 2481.882971202169s

